### ISSUE TITLE
Specificity with existing CSS

### ISSUE THREAD

**Issue by kentcdodds** [threepointone/glamor#107]
So I'd like to be able to have deterministic specificity priority to glamor styles when working with an existing framework (like bootstrap). I realize there are workarounds, but I'd like to do as little weird stuff as possible. So what if glamor add an ID to all of its CSS rules? Then it would almost always be more specific.

I actually did this in a previous project. Basically, if there was already an `id` on the `body`, it would use that one, otherwise it would generate a random one and apply it to the `body`. Then all rules would be:

```css
#random-id-123 .css-selector-stuff {
  /* rules that clash with framework stuff */
}
```

With the ID in there, it would be more specific 99% of the time.

**Comment by kentcdodds** [comment]
So here's a plugin that does this:

```javascript
import {plugins} from 'glamor'

plugins.add(specific)

function specific({selector, style}) {
  const newSelector = selector
    .split(',')
    .map(s => `#root ${s}`)
    .join(',')
  return {selector: newSelector, style}
}
```

But I noticed something else. If I load bootstrap _before_ I render glamor stuff then I don't have to worry about specificity as much. Still, I think it'd be great if I could do:

```
import {importantStyle} from 'glamor'
```

And get `!important` on all the styles. Or do the ID thing... Either/or/both. I think that'd be really handy.

**Comment by davidkpiano** [comment]
@kentcdodds No need for a plugin - the below technique will work with any selectors, regardless of if the ID exists:

```css
:not(#fake-id) .css-selector-stuff {
  /* big specificity! */
}

.css-selector-stuff:not(#fake-id) {
  /* also big specificity! */
}
```

**Comment by kentcdodds** [comment]
Cool! How would you get that without a plugin and without authoring your styles in a weird way?

**Comment by threepointone** [comment]
is this plugin something you want in core? or does it work well enough for you?

**Comment by kentcdodds** [comment]
The use case of using glamor with an existing CSS framework seems pretty common to me, especially whole people transition to CSS in JS. This is why Aphrodite's default behavior is to put `!important` on everything. So it arms to me that glamor would be more compelling if it had a solution for this out of the box.

**Comment by threepointone** [comment]
yeah but the workaround seems simple enough, including bootstrap / other css frameworks before scripts? I'm trying to avoid adding anything more into the selector by _default_, and happy to include  this plugin in the docs. 

I'm also considering a helper that simply pushes up / pulls down glamor's style tag in `<head>` (like a photoshop layer). so you could call `lowerStyleSheet` or `raiseStyleSheet`, maybe.

And for one off cases, you can use contextual selectors to kick up specificity
`style({ '&&' : { color: 'red' }})`

[and tbh, I don't personally like aph's !important behavior, though I see the value]

**Comment by kentcdodds** [comment]
Alrighty, I created a nice demo of the plugin [here](https://jsbin.com/fufefup/edit?html,output). I'm actually thinking that the whole problem would be solved if glamor's style tag was inserted at the bottom of `<head>` or even `<body>`. Any reason to not do that?

**Comment by threepointone** [comment]
No reason, I think I'll do so. Will leave this issue open till then.

**Comment by threepointone** [comment]
So... glamor already does this. But I can't protect against when js itself adds a style tag to head, overriding glamor classes. Open to ideas (or maybe just documentation would help)

**Comment by kentcdodds** [comment]
> So... glamor already does this

Hmm... It appears based on [this example](https://output.jsbin.com/fufefup) it appears that glamor is adding the `style` tag to the top of the `head`. I think that it should go at the bottom of `head` or `body`.

**Comment by threepointone** [comment]
that's because it's including the script way up in `<head>`, and the script runs, and appends a child to `head`, and then `.thing` is defined. that's probably a jsbin thing.

**Comment by kentcdodds** [comment]
Ah, interesting. It appears that if I put the glamor unpkg script at the bottom of the head then the `style` appears at the bottom. So the it appears that glamor creates and inserts its style tag not at first-rule-insert-time, but rather at library-loaded time. Hmmm... Seems slightly problematic to me. I prefer modules not do anything when they're loaded and defer stuff to when their own functions are invoked. But probably not a huge issue. Thanks!

As for this issue... I don't think that I have any immediate needs for this, but I expect having a built-in mechanism for increasing the specificity of a selector would be a useful thing, so I'll leave this open :)

**Comment by szchenghuang** [comment]
Expecting a simple control over the specificity. I end up with a plugin which simply appends `!important` for now.

**Comment by threepointone** [comment]
Whatever works for you 👍🏽Be warned that you cannot use the `style={}` prop to override styles for those elements, unless you use !important on those too.

**Comment by threepointone** [comment]
so there are 3 options -
1. use a plugin to add an id selector into every rule 
2. load glamor/bundle as late as possible (most likely?)
3. use `&&` to kick up specificity for the one off selector

I'll *eventually* get around to allowing custom tags (need it to solve #38), or if anyone faces any problems, whichever comes first. closing for now, cheers.

**Comment by winterbe** [comment]
@threepointone 

I've stumbled upon the same issue while evaluating Glamor `2.20.40` on a small project using the following  `index.html`:

```html
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <title>MyApp</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" crossorigin="anonymous">
</head>
<body>
<div id="app"></div>
<script type="text/javascript" src="/bundle.js"></script>
</body>
</html>
```

### The problem

With this setup Bootstrap sometimes is more specific than Glamor. E.g. look at this example:
```
<div className="jumbotron">
  <p {...(css({marginBottom: 100})}>boo</p>
</div>
```

In this case `marginBottom` from Glamor is overridden by Bootstrap because it defines a CSS rule `.jumbotron > p`.

### Possible solutions

I first thought the plugin from @kentcdodds is a decent solution to the problem (using `#app` as prefix for every css rule). However this breaks global styles like this `css.global('html', {...})`.

The third solution via `&&` is an ugly code smell which I want to avoid if possible.

The second solution doesn't seem to work:

> load glamor/bundle as late as possible (most likely?)

Correct me if I'm wrong but in my setup Glamor (included in `bundle.js`) is loaded after `bootstrap.css` is linked in `<head>`. Glamor adds `<style>` elements to the header after the bootstrap `<link>` element.

Can you please point me to the right direction?

Thanks in advance.

**Comment by tacomanator** [comment]
@threepointone @winterbe loading the glamorous bundle later generally won't help: order is only taken into account for rules with the same specificity (otherwise specificity is pointless).

The docs now have a section [increasing specificity](https://glamorous.rocks/examples/#increase-specificity), which I believe prepends the body id to the style.

You could also consider using inline styles instead of a plugin, especially where there are only a few issues. A plugin could just escalate the 'specificity war,' and may introduce unintended consequences elsewhere if introducing into an existing app. An inline style simple and adaptable, and has a specificity high enough to all but guarantee the intended result.
