### ISSUE TITLE
empty `merge` results in class="[object Object]"

### ISSUE THREAD

**Issue by jessehart** [threepointone/glamor#115]
i have a base component that is internally used by all my other components and provides an API for common styles+theming. in some cases, this component receives no styling requests so the `merge` gets no objects resulting in class="[object Object]"

thoughts on how to avoid this?

**Comment by threepointone** [comment]
hmm good point, I never tested null styles with classnames. I'll try fixing this by adding a toString to the null style object. 
a workaround for now is to use data attributes instead of classnames instead? And/Or detect the empty object `{}` and not add it if so.  Sorry if this isn't very satisfying :| I'll fix this soon.

**Comment by threepointone** [comment]
this is fixed, and will be live in 2.20. sorry for the trouble!

**Comment by jessehart** [comment]
no worries at all. thanks so much!

**Comment by threepointone** [comment]
cheers, this is live in 2.20.1
