### ISSUE TITLE
insertRule only support once rule in production ?

### ISSUE THREAD

**Issue by morlay** [threepointone/glamor#130]
When `NODE_ENV=development`,

`InsertRule` will work with the codes below
```js
insertRule(`
body { color: red }
#root { color: blue }
`)
```
But when `NODE_ENV=production`

It will only work with this.
```js
insertRule(`body { color: red }`)

insertRule(`#root { color: blue }`)
```

Wrong usage ?

**Comment by threepointone** [comment]
Yes, you need to insert rules one by one. It 'works' in development mode because it attaches text directly to a style tag, and the browser parses everything. in production mode, we use CSSStylesheet.insertRule, which only allows one rule at a time. I'm open to ideas as to how to detect multiple rules in development mode, so I can throw an error/ log a warning.

**Comment by threepointone** [comment]
closing this for now, lemme know if you have any ideas.
