### ISSUE TITLE
Using css to generate a string for a className doesn't have the right TypeScript type

### ISSUE THREAD

**Issue by chexee** [threepointone/glamor#193]
If I use `css(...)` to generate a string to use as a className, I need to cast it as a string, otherwise I get this TypeScript error:

```
Argument of type 'StyleAttribute' is not assignable to parameter of type 'string'.
```

**Comment by otbe** [comment]
Whats your use case? Something like:
```jsx
<div className={css(...)}/> {/* fails */}
<div className={css(...).toString()}/> {/* works */}
<div className={css(...) + ' my-class'}/> {/* works */}
```

I think its legit that TS forces you to call ```toString()``` or to kick off a type conversion by concatenating.

See [this](http://www.typescriptlang.org/play/#src=const%20s%20%3D%20%7B%0D%0A%09foo%3A%20'bar'%2C%0D%0A%09toString()%20%7B%0D%0A%09%09return%20this.foo%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Afunction%20test(s%3A%20string)%20%7B%0D%0A%09console.log(s)%3B%0D%0A%7D%0D%0A%0D%0Atest(s)%0D%0Atest(s.toString())) playground example. 

I wonder what we can do there :/

**Comment by ChristopherBiscardi** [comment]
css() returns an object that looks like

```javascript
{
  'data-css-<hash>': '',
  toString: () => 'css-<hash>'
}
```

With this object you can spread it onto an element and it will get a `data-` property, which is targeted by the compiled styles.

To get the className you have to coerce to a string. Since React allows objects in props, it seems legitimate that you have to do the coercion by calling `toString()` or implicitly via a template string \`${css(...)}\` to not get typescript errors.

**Comment by chexee** [comment]
coercing to string sounds like a good solution to me :) I wasn't sure what the type expectation should be, as the examples show it being used without coercion.
