### ISSUE TITLE
Possible to choose what's prefixed

### ISSUE THREAD

**Issue by souporserious** [threepointone/glamor#250]
Is there a way we can control what we want to be prefixed? Ending up with some pretty heavy styles because the CSS `calc` fallback.

![image](https://cloud.githubusercontent.com/assets/2762082/25793025/f3e5127e-337e-11e7-900d-983106961a09.png)

Maybe that prefix can be removed? [Support seems pretty solid now](https://caniuse.com/#search=calc).

**Comment by ChristopherBiscardi** [comment]
Prefixes are determined by a [vendored version](https://github.com/threepointone/glamor/tree/v3/packages/glamor/src/inline-style-prefix-all) of [inline-style-prefixer](https://github.com/rofrischmann/inline-style-prefixer). Which browser/version are you seeing the calc fallback in?

There is also [glamor-calc-reduction](https://www.npmjs.com/package/glamor-calc-reduction) which may help for reducible `calc`'s (but likely won't for the example you show here because of mixed units).

**Comment by souporserious** [comment]
I'm seeing it in the Chrome 58.0.3029.81. Would be awesome if we could specify the browsers we want to target. Is that something you would be willing to support? I can try out a PR if so, just let me know.

**Comment by ChristopherBiscardi** [comment]
@souporserious I'd wait for @threepointone to say he'd accept the PR. I proposed a similar action in #242 and it didn't seem to be a direction he wanted the project to go. I'm maintaining a fork privately right now for changes like this :/

**Comment by souporserious** [comment]
Thought it might be cool to allow how things are prefixed as well. So maybe in development it's a little slower and prefixes based on the current browser, but when in production it adds all of the prefixes. Right now the devtools experience is kind of rough since there are so many prefixes being added.

**Comment by threepointone** [comment]
as mentioned in another comment, recommend you whack out the plugins and add your own for bespoke behaviour.
