### ISSUE TITLE
Typescript compiling issues

### ISSUE THREAD

**Issue by leoalves** [threepointone/glamor#287]
I updated to glamor 3.0.0-2 and my typescript compiler is complaining about line 23 in index.d.ts
`export { insertRule, insertGlobal, keyframes, fontFace };`
with error TS2304: Cannot find name 'insertRule'

**Comment by donaldpipowitch** [comment]
Strange. I can verify this. Seems like the declarations are broken. It looks like I always tested the real TypeScript files instead of the declarations before. (I used a webpack setup which also compiles  dependencies, so I always imported `src/index.ts` (symlinked for development) instead of `lib/src/index.d.ts`.) Maybe this is actually a bug inside TypeScript when declarations are generated. I'll need to look into that.

**Comment by donaldpipowitch** [comment]
I reported this bug and will make a quick fix: https://github.com/Microsoft/TypeScript/issues/17085

**Comment by donaldpipowitch** [comment]
Should be fixed with `glamor@3.0.0-3`. :)
