### ISSUE TITLE
Glamor adoption questions

### ISSUE THREAD

**Issue by kennetpostigo** [threepointone/glamor#86]
Hey, I'm on the brink or releasing a component library but ran into a hurdle with aphrodite. Wondering if glamor behaves the differently as in allows the styles to be overridden by user created css. Could you take a look at the issue I raised [here](https://github.com/Khan/aphrodite/issues/163). I would love to switch in glamor if it doesn't behave the same in that aspect.

**Comment by threepointone** [comment]
No, I suppose glamor would have the same problem. Rather, this is more a problem with css than glamor / aphrodite. And I wouldn't move the tags to the top of head, this would be confusing to the user. 

Could you component library accept style objects instead of classnames? You could merge those in and you'd get expected behavior.

**Comment by kennetpostigo** [comment]
@threepointone I was planning on supporting both classNames and style objects. In any case thanks!

**Comment by threepointone** [comment]
closing this issue for now. assuming this classname is a class from the developer's own stylesheet, not a glamor / aph classname, not much we can do, sorry :|
