### ISSUE TITLE
Convert CSS to glamor: (Use Case -> Using Pre-built Component Library)

### ISSUE THREAD

**Issue by ugiacoman** [threepointone/glamor#96]
Is there a util to convert CSS to glamor? I'd like to use pre-built component libraries such as `react-toolbox`. It'd be nice to be able to convert their css to glamor to be able to use in a framework such as next.js

**Comment by threepointone** [comment]
This is a great idea, let me think about it and get back to you

**Comment by threepointone** [comment]
turns out this is not easy to do, because css frameworks use classnames for a variety of purposes. so a general purpose util wouldn't really exist. best bet is to implement something from scracth, I'm afraid. another option is to use glamor with js friendly css libs like tachyons-js https://github.com/jongold/tachyons-js

closing this for now, lemme know if you have any further leads.
